# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish rn-torus-image-viewing

# on:
#   release:
#     types: [created]

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn
        run: npm install -g yarn

      - run: yarn install
      - run: yarn postversion

  publish:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
